<?php

use App\Model\User;
use App\Enum\Routes;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer|HelperTrait $this */

$title = 'Users';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<?= $this->headTitle( $title )->setSeparator( ' - ' )->setAutoEscape( false ) ?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="icon" type="image/x-icon" href="<?= $this->basePath().'/img/favicon.ico' ?>"/>
</head>
<body class="is-light is-fullheight">
<?= $this->partial( 'partial/navbar' ); ?>
<?= $this->navigation( 'navigation' )->breadcrumbs()->setMinDepth( 0 )->setPartial( 'partial/breadcrumb' ) ?>
<section>
	<?php $FM = $this->flashMessenger()
	                 ->setMessageOpenFormat( '<div class="column is-8 is-offset-2"><article%s><div class="message-header"><p></p><button class="delete is-right" aria-label="delete"></button></div><div class="message-body">' )
	                 ->setMessageSeparatorString( '</div><div>' )
	                 ->setMessageCloseString( '</div></article></div>' );
	echo $FM->render( 'success', [ 'message', 'is-success' ] );
	echo $FM->render( 'info', [ 'message', 'is-info' ] );
	echo $FM->render( 'error', [ 'message', 'is-danger' ] ); ?>
	<?= $this->content ?>
</section>

<?= $this->inlineScript()->appendFile( $this->basePath( 'js/index.bundle.js' ) ) ?>
</body>
</html>
