version: "3.7"

services:
  users-app:
    build:
      context: "_docker"
    container_name: users-app
    restart: always
    volumes:
      - ./:/var/www
      - ./_docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - mariadb
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: US/Eastern

  mariadb:
    image: mariadb:latest
    container_name: users-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./_docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - users-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: US/Eastern

  redis:
    image: redis:latest
    container_name: users-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - users-redis-volume:/data
    environment:
      TZ: US/Eastern

volumes:
  users-db-volume:
  users-redis-volume: