version: "3.7"

services:
  users-app:
    build:
      context: "_php"
    container_name: users-app
    restart: always
    volumes:
      - ./html:/var/www
      - ./_apache:/etc/apache2/sites-available
    links:
      - mariadb
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: US/Eastern

  mariadb:
    image: mariadb:latest
    container_name: users-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./_db:/docker-entrypoint-initdb.d
      - users-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: US/Eastern

volumes:
  users-db-volume: