<?php

use App\Model\User;
use App\Enum\Routes;
use App\Form\User\DeleteForm;
use App\Model\Values\IdentityFields as IFs;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var User $User */
/** @var DeleteForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Delete User';
$this->headTitle( $title );

$password = $Form->get( IFs::PASSWORD )
                 ->setAttribute( 'class', 'form-control toggle-password' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Current Password' );

$Submit = $Form->get( 'delete' )
               ->setAttribute( 'class', 'btn btn-danger' );

$Form->setAttribute( 'action', $this->url( Routes::USER_DELETE, [ 'action' => 'delete' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1><?= $title ?></h1>
    </div>
    <div class="card-body">
		<?= $this->form()->openTag( $Form ) ?>
        <div class="alert alert-danger">
            If you are sure you want to delete your user, enter your password and click Delete.
        </div>
        <hr>

        <div class="form-group">
			<?= $this->formLabel( $password ) ?>
			<?= $this->formElement( $password ) ?>
			<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
        </div>

		<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?> Show Password

		<?= $this->formElement( $Form->get( 'security' ) ) ?>

        <div class="text-right">
			<?= $this->formSubmit( $Submit ) ?>
        </div>
		<?= $this->form()->closeTag() ?>
    </div>
</div>
<?php $this->inlineScript()->appendFile( $this->basePath( 'js/togglePassword.bundle.js' ) ) ?>