<?php

use App\Model\User;
use App\Enum\Routes;
use App\Form\User\DeleteForm;
use App\Model\Values\IdentityFields as IFs;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var User $User */
/** @var DeleteForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Delete User';
$this->headTitle( $title );

$password = $Form->get( IFs::PASSWORD );
$Submit   = $Form->get( 'delete' );

$Form->setAttribute( 'action', $this->url( Routes::USER_DELETE, [ 'action' => 'delete' ] ) )->prepare();
?>
    <div class="container has-text-centered">
        <div class="column is-6 is-offset-3">
            <div class="card">
                <header class="card-header">
                    <h1 class="title px-3 py-3"><?= $title ?></h1>
                </header>
                <div class="card-content">
					<?= $this->form()->openTag( $Form ) ?>
                    <article class="message is-danger">
                        <div class="message-body">
                            If you are sure you want to delete your user, enter your password and click Delete.
                        </div>
                    </article>
                    <hr>

                    <div class="has-text-left">
                        <div class="field">
							<?= $this->formLabel( $password ) ?>
                            <div class="control">
								<?= $this->formElement( $password ) ?>
								<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
                            </div>
                        </div>

						<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?>
                    </div>

					<?= $this->formElement( $Form->get( 'security' ) ) ?>

                    <div class="buttons is-right">
						<?= $this->formSubmit( $Submit ) ?>
                    </div>
					<?= $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
    </div>
<?php $this->inlineScript()->appendFile( $this->basePath( 'js/togglePassword.bundle.js' ) ) ?>