<?php

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use App\Enum\Routes;
use App\Form\User\InfoForm;
use App\Model\{User, UserLogin};
use App\Model\Values\{IdentityFields as IFs, UserFields as UFs};

/** @var User $User */
/** @var InfoForm $Form */
/** @var ?UserLogin $UserLogin */
/** @var PhpRenderer|HelperTrait $this */

$title = 'User Info';
$this->headTitle( $title );

$userID    = $Form->get( UFs::ID )->setValue( $User->getId() );
$userName  = $Form->get( IFs::NAME )->setValue( $User->getName() );
$updateOn  = $Form->get( IFs::UPDATED_ON )->setValue( $User->getUpdatedOn() );
$createdOn = $Form->get( IFs::CREATED_ON )->setValue( $User->getCreatedOn() );

$Form->prepare();
?>
<div class="container has-text-centered">
    <div class="column is-6 is-offset-3">
        <div class="card">
            <header class="card-header">
                <h1 class="title px-3 py-3"><?= $title ?></h1>
            </header>
            <div class="card-content">
				<?= $this->form()->openTag( $Form ); ?>
                <div class="has-text-left">
                    <div class="field">
						<?= $this->formLabel( $userID ) ?>
                        <div class="control">
							<?= $this->formElement( $userID ) ?>
							<?= $this->formElementErrors()->render( $userID, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $userName ) ?>
                        <div class="control">
							<?= $this->formElement( $userName ) ?>
							<?= $this->formElementErrors()->render( $userName, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $updateOn ) ?>
                        <div class="control">
							<?= $this->formElement( $updateOn ) ?>
							<?= $this->formElementErrors()->render( $updateOn, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $createdOn ) ?>
                        <div class="control">
							<?= $this->formElement( $createdOn ) ?>
							<?= $this->formElementErrors()->render( $createdOn, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>
                </div>
				<?= $this->form()->closeTag() ?>

				<?php if( !empty( $UserLogin ) ) { ?>
                    <hr>
                    <div class="field">
                        <label for="lastLogin" class="label">Last Login:</label>
                        <div class="control">
                            <input type="text" id="lastLogin" name="lastLogin" class="form-control" placeholder="Chrome" readonly="readonly" value="<?= $UserLogin->getLoginTime() ?> to <?= $UserLogin->getLogoutTime() ?>">
                        </div>
                    </div>
				<?php } ?>
            </div>
            <footer class="card-footer columns">
                <div class="column is-left">
                    <a href="/<?= Routes::USER_UPDATE ?>">Change Password</a>
                </div>
                <div class="column is-right">
                    <a href="/<?= Routes::USER_DELETE ?>" class="text-danger">Delete User</a>
                </div>
            </footer>
        </div>
    </div>
</div>