<?php

use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;
use App\Enum\Routes;
use App\Form\User\InfoForm;
use App\Model\Values\IdentityFields as IFs;

/** @var InfoForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'User Login';
$this->headTitle( $title );

$name     = $Form->get( IFs::NAME );
$password = $Form->get( IFs::PASSWORD );
$Submit   = $Form->get( 'login' );

$Form->setAttribute( 'action', $this->url( Routes::USER_LOGIN, [ 'action' => 'login' ] ) )->prepare();
?>
    <div class="container has-text-centered">
        <div class="column is-6 is-offset-3">
            <div class="card">
                <header class="card-header">
                    <h1 class="title px-3 py-3"><?= $title ?></h1>
                </header>
                <div class="card-content">
					<?= $this->form()->openTag( $Form ) ?>
                    <div class="has-text-left">
                        <div class="field">
							<?= $this->formLabel( $name ) ?>
                            <div class="control">
								<?= $this->formElement( $name ) ?>
								<?= $this->formElementErrors()->render( $name, [ 'class' => 'help-block' ] ) ?>
                            </div>
                        </div>

                        <div class="field">
							<?= $this->formLabel( $password ) ?>
                            <div class="control">
								<?= $this->formElement( $password ) ?>
								<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
                            </div>
                        </div>

						<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?>
                    </div>

					<?= $this->formElement( $Form->get( 'security' ) ) ?>

                    <div class="buttons is-right">
						<?= $this->formSubmit( $Submit ) ?>
                    </div>

					<?= $this->form()->closeTag() ?>
                </div>
                <footer class="card-footer has-text-left">
                    <div class="py-3 px-3">
                        Don't have an account? <a href="/<?= Routes::USER_SIGNUP ?>">Sign up</a>.
                    </div>
                </footer>
            </div>
        </div>
    </div>
<?php $this->inlineScript()->appendFile( $this->basePath( 'js/togglePassword.bundle.js' ) ) ?>