<?php

use App\Enum\Routes;
use App\Form\User\SignupForm;
use App\Model\Values\IdentityFields as IFs;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var SignupForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'User Sign Up';
$this->headTitle( $title );

$name           = $Form->get( IFs::NAME );
$password       = $Form->get( IFs::PASSWORD );
$verifyPassword = $Form->get( SignupForm::VERIFY_PASSWORD );
$Submit         = $Form->get( 'signup' );

$Form->setAttribute( 'action', $this->url( Routes::USER_SIGNUP, [ 'action' => 'signup' ] ) )->prepare();
?>
    <div class="container has-text-centered">
        <div class="column is-6 is-offset-3">
            <div class="card">
                <header class="card-header">
                    <h1 class="title px-3 py-3"><?= $title ?></h1>
                </header>
                <div class="card-content">
					<?= $this->form()->openTag( $Form ) ?>
                    <div class="has-text-left">
                        <div class="field">
							<?= $this->formLabel( $name ) ?>
                            <div class="control">
								<?= $this->formElement( $name ) ?>
								<?= $this->formElementErrors()->render( $name, [ 'class' => 'help-block' ] ) ?>
                            </div>
                        </div>

                        <div class="field">
							<?= $this->formLabel( $password ) ?>
                            <div class="control">
								<?= $this->formElement( $password ) ?>
								<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
                                <small id="passwordHelpBlock" class="form-text text-muted">
                                    Password must be 8 to 100 characters.
                                </small>
                            </div>
                        </div>

                        <div class="field">
							<?= $this->formLabel( $verifyPassword ) ?>
                            <div class="control">
								<?= $this->formElement( $verifyPassword ) ?>
								<?= $this->formElementErrors()->render( $verifyPassword, [ 'class' => 'help-block' ] ) ?>
                                <small id="verifyPasswordHelpBlock" class="form-text text-muted">
                                    Re-enter Password.
                                </small>
                            </div>
                        </div>

						<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?>
                    </div>

					<?= $this->formElement( $Form->get( 'security' ) ) ?>

                    <div class="buttons is-right">
						<?= $this->formSubmit( $Submit ) ?>
                    </div>
					<?= $this->form()->closeTag() ?>
                </div>
                <footer class="card-footer has-text-left">
                    <div class="py-3 px-3">
                        Already have an account? <a href="/<?= Routes::USER_LOGIN ?>">Login</a>.
                    </div>
                </footer>
            </div>
        </div>
    </div>
<?php $this->inlineScript()->appendFile( $this->basePath( 'js/togglePassword.bundle.js' ) ) ?>