<?php

use App\Model\User;
use App\Form\DeleteForm;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var User $User */
/** @var DeleteForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Delete User';
$this->headTitle( $title );

$password = $Form->get( 'password' )
                 ->setAttribute( 'class', 'form-control toggle-password' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Current Password' );

$submit = $Form->get( 'delete' )
               ->setAttribute( 'class', 'btn btn-danger' );

$Form->setAttribute( 'action', $this->url( 'user/delete', [ 'action' => 'index' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
    <div class="card">
        <div class="card-header">
            <h1><?= $title ?></h1>
        </div>
        <div class="card-body">
			<?= $this->form()->openTag( $Form ) ?>
            <div class="alert alert-danger">
                If you are sure you want to delete your user, enter your password and click Delete.
            </div>
            <hr>

            <div class="form-group">
				<?= $this->formLabel( $password ) ?>
				<?= $this->formElement( $password ) ?>
				<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
            </div>

			<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?> Show Password

			<?= $this->formElement( $Form->get( 'security' ) ) ?>

            <div class="text-right">
				<?= $this->formSubmit( $submit ) ?>
				<?= $this->formHidden( $Form->get( 'id' )->setValue( $User->getId() ) ) ?>
				<?= $this->formHidden( $Form->get( 'username' )->setValue( $User->getUserName() ) ) ?>
            </div>
			<?= $this->form()->closeTag() ?>
        </div>
    </div>
<?= $this->inlineScript()->prependFile( $this->basePath( 'js/index.js' ) ) ?>