<?php

use App\Form\InfoForm;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var InfoForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Login';
$this->headTitle( $title );

$userName = $Form->get( 'username' )
                 ->setAttribute( 'class', 'form-control' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Username' );

$password = $Form->get( 'password' )
                 ->setAttribute( 'class', 'form-control toggle-password' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Password' );

$submit = $Form->get( 'login' )
               ->setAttribute( 'class', 'btn btn-primary' );

$Form->setAttribute( 'action', $this->url( 'user/login', [ 'action' => 'index' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();
?>
    <div class="card">
        <div class="card-header">
            <h1><?= $title ?></h1>
        </div>
        <div class="card-body">
			<?= $this->form()->openTag( $Form ) ?>
            <div class="form-group">
				<?= $this->formLabel( $userName ) ?>
				<?= $this->formElement( $userName ) ?>
				<?= $this->formElementErrors()->render( $userName, [ 'class' => 'help-block' ] ) ?>
            </div>

            <div class="form-group">
				<?= $this->formLabel( $password ) ?>
				<?= $this->formElement( $password ) ?>
				<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
            </div>

			<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?> Show Password

			<?= $this->formElement( $Form->get( 'security' ) ) ?>

            <div class="text-right">
				<?= $this->formSubmit( $submit ) ?>
				<?= $this->formHidden( $Form->get( 'id' ) ) ?>
            </div>
			<?= $this->form()->closeTag() ?>
        </div>
        <div class="card-footer text-muted">
            Don't have an account? <a href="/user/signup">Sign up</a>.
        </div>
    </div>
<?= $this->inlineScript()->prependFile( $this->basePath( 'js/index.js' ) ) ?>