<?php

use App\Enum\Routes;
use App\Form\User\SignupForm;
use App\Model\Values\IdentityFields as IFs;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var SignupForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'User Sign Up';
$this->headTitle( $title );

$userName = $Form->get( IFs::NAME )
                 ->setAttribute( 'class', 'form-control' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Username' );

$password = $Form->get( IFs::PASSWORD )
                 ->setAttribute( 'class', 'form-control toggle-password' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Password' );

$verifyPassword = $Form->get( SignupForm::VERIFY_PASSWORD )
                       ->setAttribute( 'class', 'form-control toggle-password' )
                       ->setAttribute( 'required', true )
                       ->setAttribute( 'placeholder', 'Password' );

$Submit = $Form->get( 'signup' )
               ->setAttribute( 'class', 'btn btn-primary' );

$Form->setAttribute( 'action', $this->url( Routes::USER_SIGNUP, [ 'action' => 'signup' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
    <div class="card">
        <div class="card-header">
            <h1><?= $title ?></h1>
        </div>
        <div class="card-body">
			<?= $this->form()->openTag( $Form ) ?>
            <div class="form-group">
				<?= $this->formLabel( $userName ) ?>
				<?= $this->formElement( $userName ) ?>
				<?= $this->formElementErrors()->render( $userName, [ 'class' => 'help-block' ] ) ?>
            </div>

            <div class="form-group">
				<?= $this->formLabel( $password ) ?>
				<?= $this->formElement( $password ) ?>
				<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
                <small id="passwordHelpBlock" class="form-text text-muted">
                    Password must be 8 to 100 characters.
                </small>
            </div>

            <div class="form-group">
				<?= $this->formLabel( $verifyPassword ) ?>
				<?= $this->formElement( $verifyPassword ) ?>
				<?= $this->formElementErrors()->render( $verifyPassword, [ 'class' => 'help-block' ] ) ?>
                <small id="verifyPasswordHelpBlock" class="form-text text-muted">
                    Re-enter password.
                </small>
            </div>

			<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?> Show Passwords

			<?= $this->formElement( $Form->get( 'security' ) ) ?>

            <div class="text-right">
				<?= $this->formSubmit( $Submit ) ?>
            </div>
			<?= $this->form()->closeTag() ?>
        </div>
        <div class="card-footer text-muted">
            Already have a account? <a href="/<?= Routes::USER_LOGIN ?>">Login</a>.
        </div>
    </div>
<?= $this->inlineScript()->prependFile( $this->basePath( 'js/index.js' ) ) ?>