<?php

use App\Model\User;
use App\Enum\Routes;
use App\Form\User\UpdateForm;
use App\Model\Values\IdentityFields as IFs;
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var User $User */
/** @var UpdateForm $Form */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Update User Password';
$this->headTitle( $title );

$currentPassword = $Form->get( UpdateForm::CURRENT_PASSWORD )
                        ->setAttribute( 'class', 'form-control toggle-password' )
                        ->setAttribute( 'required', true )
                        ->setAttribute( 'placeholder', 'Current Password' );

$newPassword = $Form->get( IFs::PASSWORD )
                    ->setAttribute( 'class', 'form-control toggle-password' )
                    ->setAttribute( 'required', true )
                    ->setAttribute( 'placeholder', 'New Password' );

$verifyNewPassword = $Form->get( UpdateForm::VERIFY_NEW_PASSWORD )
                          ->setAttribute( 'class', 'form-control toggle-password' )
                          ->setAttribute( 'required', true )
                          ->setAttribute( 'placeholder', 'New Password' );

$submit = $Form->get( 'update' )
               ->setAttribute( 'class', 'btn btn-primary' );

$Form->setAttribute( 'action', $this->url( Routes::USER_UPDATE, [ 'action' => 'update' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1><?= $title ?></h1>
    </div>
    <div class="card-body">
		<?= $this->form()->openTag( $Form ) ?>
        <div class="form-group">
			<?= $this->formLabel( $currentPassword ) ?>
			<?= $this->formElement( $currentPassword ) ?>
			<?= $this->formElementErrors()->render( $currentPassword, [ 'class' => 'help-block' ] ) ?>
        </div>

        <div class="form-group">
			<?= $this->formLabel( $newPassword ) ?>
			<?= $this->formElement( $newPassword ) ?>
			<?= $this->formElementErrors()->render( $newPassword, [ 'class' => 'help-block' ] ) ?>
            <small id="newPasswordHelpBlock" class="form-text text-muted">
                New password must be different than the current password. Password must be 8 to 100 characters.
            </small>
        </div>

        <div class="form-group">
			<?= $this->formLabel( $verifyNewPassword ) ?>
			<?= $this->formElement( $verifyNewPassword ) ?>
			<?= $this->formElementErrors()->render( $verifyNewPassword, [ 'class' => 'help-block' ] ) ?>
            <small id="verifyNewPasswordHelpBlock" class="form-text text-muted">
                Re-enter new password.
            </small>
        </div>

		<?= $this->partial( 'partial/togglepasswordcheckbox' ) ?> Show Passwords

		<?= $this->formElement( $Form->get( 'security' ) ) ?>

        <div class="text-right">
			<?= $this->formSubmit( $submit ) ?>
        </div>
		<?= $this->form()->closeTag() ?>
    </div>
</div>