<?php

use User\Form\SignupForm;

$title = 'Sign Up';
$this->headTitle( $title );

/* @var SignupForm $Form */
$userName = $Form->get( 'username' )
                 ->setAttribute( 'class', 'form-control' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Username' );

$password = $Form->get( 'password' )
                 ->setAttribute( 'class', 'form-control' )
                 ->setAttribute( 'required', true )
                 ->setAttribute( 'placeholder', 'Password' );

$verifyPassword = $Form->get( 'verify-password' )
                       ->setAttribute( 'class', 'form-control' )
                       ->setAttribute( 'required', true )
                       ->setAttribute( 'placeholder', 'Password' );

$submit = $Form->get( 'signup' )
               ->setAttribute( 'class', 'btn btn-primary' );

$Form->setAttribute( 'action', $this->url( 'user/signup', [ 'action' => 'index' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1><?= $title ?></h1>
    </div>
    <div class="card-body">
		<?php
		echo $this->form()->openTag( $Form ); ?>
        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $userName ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $userName ) ?>
					<?= $this->formElementErrors()->render( $userName, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $password ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $password ) ?>
					<?= $this->formElementErrors()->render( $password, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $verifyPassword ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $verifyPassword ) ?>
					<?= $this->formElementErrors()->render( $verifyPassword, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

		<?= $this->formElement( $Form->get( 'security' ) ) ?>

        <div class="text-right">
			<?php
			echo $this->formSubmit( $submit );
			echo $this->formHidden( $Form->get( 'id' ) );
			?>
        </div>
		<?= $this->form()->closeTag() ?>
    </div>
    <div class="card-footer text-muted">
        Already have a account? <a href="/user/login">Login</a>.
    </div>
</div>