<?php

use User\Form\UpdateForm;
use User\Model\User;

/* @var UpdateForm $Form */
/* @var User $User */

$title = 'Update Password';
$this->headTitle( $title );

$currentPassword = $Form->get( 'current_password' )
                        ->setAttribute( 'class', 'form-control' )
                        ->setAttribute( 'required', true )
                        ->setAttribute( 'placeholder', 'Current Password' );

$newPassword = $Form->get( 'password' )
                    ->setAttribute( 'class', 'form-control' )
                    ->setAttribute( 'required', true )
                    ->setAttribute( 'placeholder', 'New Password' );

$verifyNewPassword = $Form->get( 'verify_new_password' )
                          ->setAttribute( 'class', 'form-control' )
                          ->setAttribute( 'required', true )
                          ->setAttribute( 'placeholder', 'New Password' );

$submit = $Form->get( 'update' )
               ->setAttribute( 'class', 'btn btn-primary' );

$Form->setAttribute( 'action', $this->url( 'user/update', [ 'action' => 'index' ] ) )
     ->setAttribute( 'method', 'post' )
     ->setAttribute( 'autocomplete', 'off' )
     ->prepare();

?>
<div class="card">
    <div class="card-header">
        <h1><?= $title ?></h1>
    </div>
    <div class="card-body">
		<?= $this->form()->openTag( $Form ) ?>
        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $currentPassword ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $currentPassword ) ?>
					<?= $this->formElementErrors()->render( $currentPassword, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $newPassword ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $newPassword ) ?>
					<?= $this->formElementErrors()->render( $newPassword, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-2">
					<?= $this->formLabel( $verifyNewPassword ) ?>
                </div>
                <div class="col-10">
					<?= $this->formElement( $verifyNewPassword ) ?>
					<?= $this->formElementErrors()->render( $verifyNewPassword, [ 'class' => 'help-block' ] ) ?>
                </div>
            </div>
        </div>

		<?= $this->formElement( $Form->get( 'security' ) ) ?>

        <div class="text-right">
			<?php
			echo $this->formSubmit( $submit );
			echo $this->formHidden( $Form->get( 'id' )->setValue( $User->getId() ) );
			echo $this->formHidden( $Form->get( 'username' )->setValue( $User->getUserName() ) );
			?>
        </div>
		<?= $this->form()->closeTag() ?>
    </div>
</div>