<?php

use App\Form\User\InfoForm;
use App\Model\{Admin, AdminLogin};
use App\Model\Values\{IdentityFields as IFs, AdminFields as AFs};
use Laminas\Form\View\HelperTrait;
use Laminas\View\Renderer\PhpRenderer;

/** @var Admin $Admin */
/** @var InfoForm $Form */
/** @var ?AdminLogin $AdminLogin */
/** @var PhpRenderer|HelperTrait $this */

$title = 'Admin Info';
$this->headTitle( $title );

$adminID   = $Form->get( AFs::ID )->setValue( $Admin->getId() );
$name      = $Form->get( IFs::NAME )->setValue( $Admin->getName() );
$updateOn  = $Form->get( IFs::UPDATED_ON )->setValue( $Admin->getUpdatedOn() );
$createdOn = $Form->get( IFs::CREATED_ON )->setValue( $Admin->getCreatedOn() );

$Form->prepare();
?>
<div class="container has-text-centered">
    <div class="column is-6 is-offset-3">
        <div class="card">
            <header class="card-header">
                <h1 class="title px-3 py-3"><?= $title ?></h1>
            </header>
            <div class="card-content">
				<?= $this->form()->openTag( $Form ); ?>
                <div class="has-text-left">
                    <div class="field">
						<?= $this->formLabel( $adminID ) ?>
                        <div class="control">
							<?= $this->formElement( $adminID ) ?>
							<?= $this->formElementErrors()->render( $adminID, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $name ) ?>
                        <div class="control">
							<?= $this->formElement( $name ) ?>
							<?= $this->formElementErrors()->render( $name, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $updateOn ) ?>
                        <div class="control">
							<?= $this->formElement( $updateOn ) ?>
							<?= $this->formElementErrors()->render( $updateOn, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>

                    <div class="field">
						<?= $this->formLabel( $createdOn ) ?>
                        <div class="control">
							<?= $this->formElement( $createdOn ) ?>
							<?= $this->formElementErrors()->render( $createdOn, [ 'class' => 'help-block' ] ) ?>
                        </div>
                    </div>
                </div>
				<?= $this->form()->closeTag() ?>

				<?php if( !empty( $AdminLogin ) ) { ?>
                    <hr>
                    <div class="has-text-left">
                        <div class="field">
                            <label for="lastLogin" class="label">Last Login:</label>
                            <div class="control">
                                <input type="text" id="lastLogin" name="lastLogin" class="input" placeholder="Chrome" disabled="disabled" value="<?= $AdminLogin->getLoginTime() ?> to <?= $AdminLogin->getLogoutTime() ?>">
                            </div>
                        </div>
                    </div>
				<?php } ?>
            </div>
        </div>
    </div>
</div>