<nav class="breadcrumb has-succeeds-separator" aria-label="breadcrumbs">
    <ul><?php
		foreach( $this->pages as $key => $page ) {
			if( $key < count( $this->pages ) - 1 ) { ?>
                <li><a href="<?= $page->getHref() ?>"><?= $page->getLabel() ?></a></li>
			<?php } else { ?>
                <li class="is-active"><a href="<?= $page->getHref() ?>" aria-current="page"><?= $page->getLabel() ?></a></li>
			<?php }
		} ?>
    </ul>
</nav>